# Background and foreground colors
background = #7276db
foreground = #e0def4

# Standard colors
palette = 0=#7276db
palette = 1=#eb6f92
palette = 2=#9ab76d
palette = 3=#f6c177
palette = 4=#ea9a97
palette = 5=#df69ba
palette = 6=#9ccfd8
palette = 7=#e0def4

# Bright colors
palette = 8=#c4a7e7
palette = 9=#ed7f9e
palette = 10=#a7c080
palette = 11=#f8d098
palette = 12=#ebbcba
palette = 13=#e587c8
palette = 14=#b1d9e0
palette = 15=#e0def4
