# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgb(ea9a97)

general {
    col.active_border = $activeBorderColor
}

group {
    col.border_active = $activeBorderColor
}

decoration {
    rounding = 16

    blur {
        enabled = true
        size = 4
        passes = 3
        contrast = 0.95
        brightness = 0.9
        vibrancy = 0.15
        vibrancy_darkness = 0.25
        noise = 0.015
        ignore_opacity = true
        new_optimizations = on
    }

    active_opacity = 1
    inactive_opacity = 0.95
    fullscreen_opacity = 1.0
}

layerrule = blur on, match:namespace walker
layerrule = ignore_alpha 0, match:namespace walker
layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 0, match:namespace notifications
layerrule = blur on, match:namespace vicinae
layerrule = blur on, match:namespace swayosd
layerrule = ignore_alpha 0.1, match:namespace waybar
layerrule = ignore_alpha 0.1, match:namespace vicinae
