background            #7276db
foreground            #e0def4

# black
color0  #7276db
color8  #c4a7e7

# red
color1  #eb6f92
color9  #ed7f9e

# green
color2  #9ab76d
color10 #a7c080

# yellow
color3  #f6c177
color11 #f8d098

# blue
color4  #ea9a97
color12 #ebbcba

# magenta
color5  #df69ba
color13 #e587c8

#cyan
color6  #9ccfd8
color14 #b1d9e0

#white
color7  #e0def4
color15 #e0def4


